%YAML:1.0
---
# width and height of the original image in pixels
image_height: 720
image_width: 1280

# width and height in pixels of segmentation network output
# (when given the above input)
seg_height: 720
seg_width: 1280

# the width and height of the image representing a top-down view of the real world
costmap_height: 1400
costmap_width: 1400

# the number of meters per pixel (currently 0.03)
m_per_pixel: 0.1 #3.00e-02

# file path indicating where to write the file
homography_file_path: "/home/luk/ros_bsc/src/deep_nav_layers/calibrate_homography/homography.xml"

# file path pointing to sample segmentation data
seg_data_path: "/home/luk/ros_bsc/src/deep_nav_layers/calibrate_homography/segmentation-output.png"
